/**
 * Every viewer-facing string lives here.
 * English with Filipino-friendly phrasing; a Taglish variant is a swap of this
 * one file, not a hunt through JSX.
 */
export const copy = {
  appName: 'PH-Drama',
  tagline: 'Short dramas, one thumb at a time.',

  nav: {
    home: 'Home',
    reels: 'Reels',
    coins: 'Coins',
    me: 'Me',
  },

  auth: {
    signInTitle: 'Welcome back',
    signInSubtitle: 'Sign in to keep watching where you left off.',
    signUpTitle: 'Create your account',
    signUpSubtitle: 'Free to join. Episodes 1–5 of every series are on us.',
    name: 'Display name',
    namePlaceholder: 'How should we call you?',
    email: 'Email',
    emailPlaceholder: 'you@email.com',
    password: 'Password',
    passwordHint: 'At least 6 characters.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    rememberMe: 'Remember me',
    rememberHint: 'Stay signed in on this device for 30 days.',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    signUp: 'Create account',
    signingUp: 'Creating your account…',
    noAccount: 'Walang account pa?',
    haveAccount: 'Already have an account?',
    switchToSignUp: 'Create one',
    switchToSignIn: 'Sign in',
    signOut: 'Sign out',
    signingOut: 'Signing out…',
    guestNote: 'You can browse and watch the free episodes without an account.',
    browseAsGuest: 'Keep browsing',
    checkEmail: 'Almost there — confirm your email address to finish signing up.',
    badCredentials: 'That email and password did not match.',
    emailTaken: 'There is already an account with that email.',
    weakPassword: 'Use at least 6 characters.',
    invalidEmail: 'Enter a valid email address.',
    demoNote: 'Demo mode. Any email works and nothing is sent — the account lives in this browser only.',
  },

  home: {
    featured: 'Featured now',
    trending: 'Trending sa Pinas',
    newReleases: 'Bagong labas',
    continueWatching: 'Continue watching',
    browseAll: 'All series',
    freeBadge: (n: number) => `First ${n} episodes free`,
    freeBadgeShort: (n: number) => `${n} free`,
  },

  series: {
    episodes: 'Episodes',
    episodeCount: (n: number) => `${n} episodes`,
    watchFree: 'Watch free',
    resume: 'Resume',
    startFromOne: 'Start from Episode 1',
    locked: 'Locked',
    free: 'Free',
    preview: 'PREVIEW',
    previewNote:
      'Posted from the Story Studio. These episodes are free and play a placeholder clip — the story is written, the video is not rendered yet.',
  },

  player: {
    loading: 'Buffering…',
    error: 'We could not start this episode. Check your connection and try again.',
    retry: 'Try again',
    nextEpisode: 'Next episode',
    previousEpisode: 'Previous',
    tapToUnmute: 'Tap for sound',
    episodeLabel: (n: number) => `Episode ${n}`,
  },

  unlock: {
    title: 'This episode is locked',
    subtitle: 'Pick how you want to keep watching.',
    withCoins: (price: number) => `Unlock for ${price} coins`,
    withAd: 'Watch a short ad',
    adDisabled: 'Rewarded ads are coming soon.',
    goVip: 'Go VIP — all episodes, no ads',
    balanceLeft: (n: number | string) => `${n} left`,
    notEnough: 'Not enough coins. Top up to keep watching.',
    topUp: 'Top up coins',
    unlocking: 'Unlocking…',
    unlocked: 'Unlocked. Enjoy!',
    signInFirst: 'Sign in to unlock episodes.',
    signInCta: 'Sign in to continue',
  },

  coins: {
    title: 'Coins & VIP',
    subtitle: 'Pay with GCash, Maya, QR Ph or bank transfer. We confirm within 24 hours.',
    packages: 'Coin packages',
    bonus: (n: number) => `+${n} bonus`,
    popular: 'Most popular',
    vipTitle: 'VIP access',
    vipPerk1: 'Every episode of every series',
    vipPerk2: 'No ads, ever',
    vipPerk3: 'New episodes the moment they drop',
    vipActive: 'VIP active',
    buy: 'Buy',
    subscribe: 'Subscribe',
  },

  pay: {
    title: 'Complete your payment',
    step1: 'Send the exact amount',
    step2: 'Upload your receipt',
    step3: 'Wait for confirmation',
    amountDue: 'Amount due',
    chooseMethod: 'Choose how you paid',
    accountName: 'Account name',
    accountNumber: 'Number / account',
    referenceLabel: 'Reference number',
    referencePlaceholder: 'e.g. 0123456789012',
    referenceHelp: 'Copy this exactly from your receipt. Each reference can only be used once.',
    receiptLabel: 'Receipt screenshot',
    receiptHelp: 'JPG or PNG, up to 5 MB.',
    submit: 'Submit for review',
    submitting: 'Submitting…',
    submitted: 'Received! We will confirm within 24 hours.',
    duplicate: 'That reference number has already been submitted.',
    missingFields: 'Add your reference number and receipt before submitting.',
    copied: 'Copied',
  },

  me: {
    title: 'My account',
    balance: 'Coin balance',
    vipStatus: 'VIP status',
    notVip: 'Not a VIP yet',
    unlocked: 'Unlocked episodes',
    payments: 'Payment history',
    ledger: 'Coin activity',
    noPayments: 'No payments yet.',
    noUnlocks: 'Nothing unlocked yet. Episodes 1–5 of every series are free.',
    signedOutTitle: 'You are not signed in',
    signedOutBody:
      'Sign in to see your coins, your unlocked episodes and your payment history.',
  },

  admin: {
    portalName: 'PH-Drama Staff',
    title: 'Payments',
    dashboard: 'Dashboard',
    signIn: 'Staff sign in',
    signInHint: 'This portal is for PH-Drama staff. Customer accounts cannot sign in here.',
    email: 'Work email',
    password: 'Password',
    passcode: 'Demo passcode',
    passcodeHint: 'Demo mode. The passcode is in the README; the queue below only ever shows payments made in this browser.',
    signInAction: 'Sign in',
    signingIn: 'Signing in…',
    signOut: 'Sign out',
    signedInAs: 'Signed in as',
    badCredentials: 'Those details did not work.',
    notStaff: 'That account is not a staff account.',
    backToApp: 'Open the customer app',
    activity: 'Coin activity',
    revenue: 'Revenue',
    queue: 'Payment queue',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    approve: 'Approve',
    reject: 'Reject',
    note: 'Note (optional)',
    viewReceipt: 'View receipt',
    reference: 'Reference',
    emptyQueue: 'Nothing waiting for review.',
    emptyActivity: 'No coin movements yet.',
    studio: 'Story Studio',
    viewers: 'Viewers',
    viewersEmpty: 'No customers yet.',
    adjustCoins: 'Adjust coins',
    coinDelta: 'Coins to add or remove',
    coinDeltaHint: 'Use a negative number to deduct. The balance never goes below zero.',
    setVip: 'Set VIP',
    vipDays: 'Days to grant',
    vipDaysHint: 'Extends from the current expiry when VIP is still active. 0 revokes it.',
    reason: 'Reason',
    reasonRequired: 'A reason is required — it goes into the ledger.',
    apply: 'Apply',
    applying: 'Applying…',
    applied: 'Done — the ledger has the entry.',
    balanceNow: 'Balance',
    vipNow: 'VIP',
    revokeVip: 'Revoke VIP',
    superAdminOnly: 'Only a SuperAdmin can adjust coins or VIP.',

    studioTitle: 'Story Studio',
    studioSubtitle: 'Write a premise, get an episode-by-episode breakdown, then publish it as a series.',
    premise: 'Premise',
    premisePlaceholder:
      'A probinsyana takes a job as a maid in the house of the family that ruined her father. She has six months before the statute of limitations runs out.',
    seriesTitleOptional: 'Series title (optional)',
    episodeCount: 'How many episodes',
    generate: 'Write the breakdown',
    generating: 'Writing…',
    generatedBy: (model: string) => `Written by ${model}`,
    generatedLocally:
      'Outline only — no ANTHROPIC_API_KEY is set, so this was generated locally, not by a model. Set the key to get real scripts.',
    scenesHeading: 'Episodes',
    beat: 'Beat',
    hook: 'Hook',
    renderPending: 'No video yet',
    post: 'Post to reels',
    posting: 'Posting…',
    postHint:
      'Posts it to the customer reels feed right away as a free PREVIEW — the scripts are real, the video behind each episode is a placeholder until a render provider is wired up.',
    postedTo: (n: number) => `Posted. ${n} episodes are live in the reels feed now.`,
    viewInApp: 'Open it in the customer app',
    publish: 'Publish (needs rendered video)',
    publishing: 'Publishing…',
    published: 'Published',
    publishDraftNote:
      'Published as a draft — the series stays hidden from viewers until every episode has a rendered video. Use Post to reels to make it visible now as a preview.',
    savedStories: 'Saved stories',
    noStories: 'Nothing written yet.',
    demoNotPersisted:
      'Demo mode has no database, so this breakdown is not saved and cannot be published. Connect Supabase to keep stories, queue renders and publish them as a series.',
    videoPending:
      'Video rendering is not wired up: no provider is chosen yet, so every scene queues a render job and waits. See docs/BUILD_ORDER.md, Phase 10.',
  },

  status: {
    pending: 'Pending review',
    approved: 'Approved',
    rejected: 'Rejected',
  },

  errors: {
    UNAUTHENTICATED: 'Sign in to continue.',
    FORBIDDEN: 'You do not have access to that.',
    LOCKED: 'This episode is locked.',
    NOT_FOUND: 'We could not find that.',
    INSUFFICIENT_COINS: 'Not enough coins. Top up to keep watching.',
    DUPLICATE_REFERENCE: 'That reference number has already been submitted.',
    RATE_LIMITED: 'Too many tries. Give it a few minutes.',
    FEATURE_DISABLED: 'That is not switched on yet.',
    INVALID_INPUT: 'Please check the details and try again.',
    ALREADY_REVIEWED: 'That payment was already reviewed.',
    INTERNAL: 'Something went wrong on our side. Please try again.',
  },

  demo: {
    badge: 'DEMO',
    banner:
      'Demo mode — no Supabase connected. Coins, unlocks and payments are simulated in your browser so you can click through the whole app.',
    reset: 'Reset demo data',
  },
} as const;
